Email balance update
Winxton/SubShare pull request #81
Opened 2024-02-27 03:32 UTC by ninagong

2024-02-27 04:55 UTC, Winxton commented on backend/src/service/emails.ts
> +    html: `You owe ${senderName} ${subscriptionCost} for the monthly subscription. \nAs a result, your balance owed for ${groupName} has been updated to ${memberBalance}. \nHead over to the <a href="
nice text

2024-02-27 07:26 UTC, Winxton approved these changes

2024-02-27 08:36 UTC, Winxton requested changes
Nvm, still getting
```
Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
```

2024-03-04 20:12 UTC, Tome94 approved these changes
great.

2024-03-04 23:57 UTC, closed without merging